apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelfie-server
  namespace: shelfie
  labels:
    app: shelfie-server
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shelfie-server
  template:
    metadata:
      labels:
        app: shelfie-server
        version: v1
    spec:
      containers:
      - name: shelfie-server
        image: shelfie/server:latest
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: shelfie-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: shelfie-config
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: shelfie-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelfie-client
  namespace: shelfie
  labels:
    app: shelfie-client
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shelfie-client
  template:
    metadata:
      labels:
        app: shelfie-client
        version: v1
    spec:
      containers:
      - name: shelfie-client
        image: shelfie/client:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5